version: '3.9'
services:
  app:
    container_name: mzk
    build: .
    env_file:
      - .env.docker
    ports:
      - 6060:6060
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=mzk123
      - PGUSER=mzk
      - POSTGRES_DB=mzk_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
    volumes:
      - ./dbdata/postgres:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -h postgres"
      interval: 10s
      timeout: 30s
      retries: 3
  
  migration:
    image: ghcr.io/amacneil/dbmate
    container_name: dbmate
    entrypoint: dbmate -u 'postgres://mzk:mzk123@postgres:5432/mzk_db?sslmode=disable' up
    volumes:
      - ./migrations:/db/migrations
    depends_on:
      postgres:
        condition: service_healthy